apiVersion: batch/v1
kind: Job
metadata:
  name: kube-echo-test
spec:
  template:
    metadata:
      name: kube-echo-pod
    spec:
      containers:
        - name: kube-test-container
          image: kubetest
          imagePullPolicy: Never
      restartPolicy: Never